

 sudo: required

 language: node_js

 node_js:
   - '4'
   - '5'
 env:
   - CXX=g++-4.8
 addons:
   apt:
     sources:
       - ubuntu-toolchain-r-test
     packages:
       - g++-4.8



 # fail asap when there is a failure
 matrix:
   fast_finish: true

 # cache node modules
 cache:
   directories:
      node_modules

 before_install:
   # remove useless/non listed deps
  - npm prune
    # faster npm install
  - npm set progress=false

   # nyc fail on npm@3.7.1. Remove this patch when node upgrade npm
   # https://github.com/bcoe/nyc/issues/190
  - npm install -g npm@latest

 services: mongodb

 script: npm run test